### ISSUE TITLE
Java 11 path error

### ISSUE THREAD

**Issue by najmussakib1400** [codingotaku/Animu-Downloaderu#11]
can't configure the path for java 11..is it a bug..i am using windows 10 and the latest java 11.

**Comment by codingotaku** [comment]
Actually, the java path detection is automatically handled by jlink (for binary) and gradle (in source).
So most likely the environment path is not set properly,

Could you please open a new command line and type `echo %path%` and see if the path to the JDK/bin is really there?
and if you are using multiple versions of java like java 8 and java 11, make sure that java11 is accessible by checking `java --version` in commandline 

Or can you please paste the error log here?

![reading books](https://media.giphy.com/media/Tf3mp01bfrrUc/giphy.gif)

**Comment by codingotaku** [comment]
Closing as no reply from op
