### ISSUE TITLE
502 error on most titles

### ISSUE THREAD

**Issue by arnoldsecret** [codingotaku/Animu-Downloaderu#14]
![Untitled](https://user-images.githubusercontent.com/41223243/71714291-39c5aa80-2e48-11ea-8225-0b8519476c71.png)

**Comment by codingotaku** [comment]
Thank you for bringing this to notice, I hope that this is fixed in the latest commits as I have made a few changes on URL handling.
anyway I'll keep this issue open till next release.

![image](https://user-images.githubusercontent.com/10434256/71795128-9d182e00-303c-11ea-99bc-ad2386108d94.png)

**Comment by codingotaku** [comment]
@arnoldsecret could you please try again with this [alpha release](https://github.com/codingotaku/Animu-Downloaderu/releases/tag/v2.6.4-alpha)?
it has a few missing features but I think this might solve your problem.

also, I am able to download the same anime with this release.
![screen](https://user-images.githubusercontent.com/10434256/71987535-4e2dec80-3226-11ea-9d2e-5ea85f23cfcb.png)

**Comment by arnoldsecret** [comment]
I gave the update a test run and it kind of works, except for Koihime Musou ep9, all the other episodes from that series download fine.

**Comment by arnoldsecret** [comment]
closing as it seems that most other errors are isolated cases.
