### ISSUE TITLE
Please add the ability to get the download link of the episodes (maybe store them in .txt file) so that we can download via some externel downloaders like jdownloader2, idm etc. 

### ISSUE THREAD

**Issue by redfanglicker** [codingotaku/Animu-Downloaderu#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by codingotaku** [comment]
Hi, That is a great Idea. **I'll add this in the next release.**

**Note:** If there are any error during download, the server might change the video token after session expires.
My app handles it by crawling the page again in case of error.

So I really do think that downloading with animu downloaderu is better to handle such scenarios.
~~And I am downloading the video using 9 threads which is similar to most download managers.~~
[Loading...](https://media.giphy.com/media/kQ3FSVoJrkYWk/giphy.gif "Thinking my brain out to defend myself")

**Comment by codingotaku** [comment]
Closing as the dl generated will not be active after session expires, ie. When downloading a huge list, you are more likely to encounter session expired callback. My app handles it by regenerating the link and external downloader won't be able to do that.
