### ISSUE TITLE
Add another sever from twist.moe website since the episode quality there far superior than any other anime websites. 

### ISSUE THREAD

**Issue by redfanglicker** [codingotaku/Animu-Downloaderu#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by redfanglicker** [comment]
All which websites are server 1 and server 2 from?

**Comment by codingotaku** [comment]
Hi, Thank you for the suggestion,
Unfortunately twist.moe is a bit troublesome on crawling, I'll look into it and try to add this as a 3rd server in next release.

Server1 is http://anime1.com/
Server2 is http://animexd.me/
I purposefully  did not mention the servers in the app due to some policy reasons.

![Loading..](https://gifimage.net/wp-content/uploads/2017/09/anime-thinking-gif-2.gif "Thinking")

**Comment by redfanglicker** [comment]
Hi! Thanks for responding, maybe this repo https://github.com/phanirithvij/twist.moe might help you in crawling through twist.moe though now its not working. Maybe you can get some idea from that and implement in yours or not( i am not a coder so i have no idea how tough or easy it is!)

**Comment by codingotaku** [comment]
Alright, I did some research and found the following blocking issues.
1. Twist.moe doesn't have any description or anime poster :/
2. The video link is generated after the page is loaded, it may not look like much of an issue but I use Jsoup library and it is just an HTML parser. meaning it does not allow me to fetch content loaded dynamically.
3. twist is very slow in my region :/

I'll ignore the points 1 & 3 but to add twist.moe I might need to rewrite a lot of things, but rest assured, I will not abandon a twist unless I have better options.

**Comment by codingotaku** [comment]
Closing as the website is not stable on crawling. it takes 5-15 seconds to even load the video including the JS. which will heavily affect the application's performance.
