### ISSUE TITLE
server 2 dead

### ISSUE THREAD

**Issue by g4269159** [codingotaku/Animu-Downloaderu#9]
Server 2 doesn't show any videos. The site probably got taken down.

**Comment by codingotaku** [comment]
Thank you for bringing this to notice!
Server 2 will be removed on next release,
Any suggestions for new Anime servers are welcome :3

![busy](https://media.giphy.com/media/1gbQIeNzZxcSk/giphy.gif)

**Comment by g4269159** [comment]
Im not sure what site are u using as server 1 but I'd suggest any of these ones
anime1.com
animeplus.tv
animenova.org
gogoanime.io
btw It'd be great if u could add a drama website as server 3? There aren't as many downloaders for that
any of these sites would be useful
dramacool.bz
www1.ondramanice.tv
www.dramagalaxy.tv/

**Comment by codingotaku** [comment]
Server 2 is removed in new release.
@g4269159 thank you for the suggestions!
I am working on a new app to stream(without ads) and download anime. I will definitely include some of the suggested sites :100: 
Animu downloaderu has some technical limitations on websites that generated by JavaScript, and a few of the website blocked me out for trying to crawl :( 

AnimuDownloaderu might come back, may be someone else will fork and fix my spaghetti code..
but for now, we will have to stick with just Anime1 (Server1)
